import { useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileText, LayoutGrid, CreditCard, HelpCircle, AlignLeft, Upload, Download } from 'lucide-react';
import { useLectureStore, useUIStore } from '../../store/lectureStore';
import SummaryTab from './tabs/SummaryTab';
import ConceptsTab from './tabs/ConceptsTab';
import FlashcardsTab from './tabs/FlashcardsTab';
import QuizTab from './tabs/QuizTab';
import TranscriptTab from './tabs/TranscriptTab';
import { SUBJECT_COLORS } from '../../data/dummyData';
import type { Lecture } from '../../types/lecture';
import { mapBackendResponseToContent } from '../../utils/dataMapper';

const TABS = [
    { id: 'summary', label: 'Summary', icon: <FileText size={13} /> },
    { id: 'concepts', label: 'Concepts', icon: <LayoutGrid size={13} /> },
    { id: 'flashcards', label: 'Flashcards', icon: <CreditCard size={13} /> },
    { id: 'quiz', label: 'Quiz', icon: <HelpCircle size={13} /> },
    { id: 'transcript', label: 'Transcript', icon: <AlignLeft size={13} /> },
];

function EmptyState({ onUpload }: { onUpload: () => void }) {
    return (
        <div className="flex flex-col items-center justify-center h-full text-center py-20">
            <div className="w-20 h-20 rounded-3xl bg-gradient-to-br from-accent/20 to-purple-900/40 border border-accent/20 flex items-center justify-center mb-6">
                <Upload size={32} className="text-accent" />
            </div>
            <h3 className="text-xl font-semibold text-text-primary mb-2">No lecture selected</h3>
            <p className="text-sm text-text-muted max-w-xs mb-6">
                Upload an audio file and Resonance will transcribe, analyze, and generate study materials automatically.
            </p>
            <button className="btn-primary px-6 py-2.5" onClick={onUpload}>
                <Upload size={15} /> Upload Your First Lecture
            </button>
        </div>
    );
}

function downloadStudyGuide(lecture: Lecture) {
    const content = lecture.content;
    if (!content) return;
    const lines = [
        `# ${lecture.title} — Study Guide`,
        `Generated by Resonance · ${new Date().toLocaleDateString()}`,
        '',
        '## Quick Summary',
        content.shortSummary,
        '',
        '## Key Concepts',
        ...content.keyConcepts.map((c: any) => `### ${c.title}\n${c.description}`),
        '',
        '## Key Terms',
        ...content.keyTerms.map((t: any) => `**${t.term}**: ${t.definition}`),
        '',
        '## Flashcards',
        ...content.flashcards.map((f: any, i: number) => `${i + 1}. Q: ${f.question}\n   A: ${f.answer}`),
    ];
    const blob = new Blob([lines.join('\n\n')], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${lecture.title.replace(/\s+/g, '-')}-study-guide.md`;
    a.click();
    URL.revokeObjectURL(url);
}

export default function LectureViewer() {
    const activeLecture = useLectureStore((state) => 
        state.activeLectureId ? state.lectures.find(l => l.id === state.activeLectureId) : null
    );
    const { addLecture } = useLectureStore();
    const { activeTab, setActiveTab, setUploadModalOpen } = useUIStore();

    // Background Polling for Analysis
    useEffect(() => {
        if (activeLecture && !activeLecture.content && activeLecture.id.startsWith('job-')) {
            console.log('[POLL] Starting background fetch for:', activeLecture.id);
            const backendUrl = import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000';
            
            const interval = setInterval(async () => {
                try {
                    const res = await fetch(`${backendUrl}/status/${activeLecture.id}`);
                    if (!res.ok) return;
                    const data = await res.json();
                    
                    console.log(`[POLL] ${activeLecture.id} status:`, data.status);
                    
                    if (data.status === 'Completed') {
                        clearInterval(interval);
                        console.log('[POLL] Analysis complete! Mapping data...');
                        
                        const newContent = mapBackendResponseToContent(data);
                        
                        // Update the store
                        addLecture({
                            ...activeLecture,
                            content: newContent,
                            status: 'done',
                            confidenceScore: 92 // Example score
                        });
                    }
                } catch (e) {
                    console.error("[POLL] Error:", e);
                }
            }, 3000);

            return () => clearInterval(interval);
        }
    }, [activeLecture?.id, activeLecture?.content === undefined, addLecture]);

    if (!activeLecture) {
        return <EmptyState onUpload={() => setUploadModalOpen(true)} />;
    }

    return (
        <motion.div
            key={activeLecture.id}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex flex-col h-full"
        >
            {/* Lecture header */}
            <div className="px-6 pt-5 pb-4 border-b border-border-subtle">
                <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-2">
                            <span className={`tag text-[10px] font-bold ${SUBJECT_COLORS[activeLecture.subject]}`}>
                                {activeLecture.subject}
                            </span>
                            <span className="text-xs text-text-muted">
                                {new Date(activeLecture.uploadedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                            </span>
                            <span className="text-xs text-text-muted">· {activeLecture.duration}</span>
                        </div>
                        <h2 className="text-xl font-bold text-text-primary truncate">{activeLecture.title}</h2>
                    </div>

                    {/* Action buttons */}
                    <div className="flex items-center gap-2 flex-shrink-0">
                        <button className="btn-secondary text-xs" onClick={() => setUploadModalOpen(true)}>
                            <Upload size={13} /> Upload MP3
                        </button>
                        <button
                            className="btn-primary text-xs"
                            onClick={() => downloadStudyGuide(activeLecture)}
                            disabled={!activeLecture.content}
                        >
                            <Download size={13} /> Download Guide
                        </button>
                    </div>
                </div>
            </div>

            {/* Tab bar */}
            <div className="flex items-center gap-1 px-6 border-b border-border-subtle overflow-x-auto scrollbar-thin">
                {TABS.map((tab) => (
                    <button
                        key={tab.id}
                        className={`tab-item flex items-center gap-1.5 ${activeTab === tab.id ? 'tab-item-active' : ''}`}
                        onClick={() => setActiveTab(tab.id)}
                    >
                        {tab.icon}
                        {tab.label}
                    </button>
                ))}
            </div>

            {/* Tab content */}
            <div className="flex-1 overflow-y-auto scrollbar-thin p-6">
                <motion.div
                    key={`${activeLecture.id}-${activeTab}`}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.2 }}
                >
                    {activeTab === 'summary' && <SummaryTab lectureId={activeLecture.id} />}
                    {activeTab === 'concepts' && <ConceptsTab />}
                    {activeTab === 'flashcards' && <FlashcardsTab />}
                    {activeTab === 'quiz' && <QuizTab />}
                    {activeTab === 'transcript' && <TranscriptTab />}
                </motion.div>
            </div>
        </motion.div>
    );
}
